
services:
  app:
    container_name: app_pa
    build:
      context: .
      dockerfile: Dockerfile.umberto
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    volumes:
      - ./:/src/app

  db:
    container_name: db_mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./src/Db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
